variable "project_name" {}
variable "env" {}
variable "domain" {}
variable "domain_record" {}
variable "do_token" {}
variable "do_region" {}
variable "aws_key" {}
variable "aws_secret" {}
variable "aws_region" {}
variable "gitlab_token" {}
variable "gitlab_username" {}
variable "gitlab_project" {}

variable "app_key" {}
variable "google_id" {}
variable "google_secret" {}
variable "google_redirect" {}
variable "aws_bucket" {}
variable "jwt_secret" {}
variable "mail_driver" {}
variable "mail_host" {}
variable "mail_port" {}
variable "mail_username" {}
variable "mail_password" {}
variable "media_url" {}
variable "passport_id" {}
variable "passport_secret" {}
variable "queue_connection" {}
